name: Stroyrem_push


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          sudo docker build -t stroyrem .
      - name: docker run
        run: |
          chmod +w /data/credentials.py
          echo "$CREDENTIALS" > /data/credentials.py
          sudo docker run --rm stroyrem pytest -s -v tests/

