name: Stroyrem_pr

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pass credentials
        run: |
          sudo echo "${{ secrets.STROYREM_CREDENTIALS }}" > data/credentials.py
          cd data/
          echo $PWD
          ls
          cat credentials.py
      - name: docker build
        run: |
          sudo docker build -t stroyrem .
      - name: docker run
        run: |
          sudo docker run --rm stroyrem pytest -s -v tests/
