name: Stroyrem_pr

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          sudo docker build -t stroyrem .
      - name: docker run
        run: |
          sudo docker run --rm stroyrem pytest -s -v tests/